worklogger/logs/urls.py
from django.conf.urls import url

from . import views

app_name = 'logs'
urlpatterns = [
    url(r'^$', views.LogIndexView.as_view(), name='index'),
    url(r'^new/$', views.LogNew.as_view(), name='new'),
    url(r'^(?P<pk>[0-9]+)/$', views.LogDetail.as_view(), name='detail'),
    url(r'^delete/(?P<pk>\d+)/$', views.LogDelete.as_view(), name='delete'),
    url(r'^update/(?P<pk>\d+)/$', views.LogUpdate.as_view(), name='update'),
]

worklogger/worklogger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from logs.views import home

urlpatterns = [
    url(r'^logs/', include('logs.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
]

worklogger/logs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

import datetime
from datetime import timedelta
from django.utils.dateparse import parse_date


# Create your models here.

class Project(models.Model):
    project_name = models.CharField(max_length=200)

    def __str__(self):
        return self.project_name

    def get_total_hours(self):
        logs = Log.objects.filter(project=self)
        return logs.aggregate(Sum('duration'))['duration__sum']


class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, blank=False, null=True, on_delete=models.SET_NULL)
    duration = models.DecimalField(max_digits=10, decimal_places=3)
    log_date = models.DateField(auto_now=False, auto_now_add=False, default=datetime.date.today)
    date_logged = models.DateField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return str(self.project) + " - " + str(self.duration) + " - " + str(self.log_date)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_hours = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)

    def get_week_logs(self, selected_date):
        if parse_date(selected_date).weekday() == 6:
            startdate = parse_date(selected_date)
        else:
            startdate = parse_date(selected_date) - timedelta(days=parse_date(selected_date).weekday()) - timedelta(
                days=1)

        return Log.objects.filter(user=self.user,
                                  log_date__in=[startdate,
                                                startdate + timedelta(days=1),
                                                startdate + timedelta(days=2),
                                                startdate + timedelta(days=3),
                                                startdate + timedelta(days=4),
                                                startdate + timedelta(days=5),
                                                startdate + timedelta(days=6)])

    def get_month_startdate(self, selected_date):
        month = datetime.datetime.strptime(selected_date, "%Y-%m-%d").month
        year = datetime.datetime.strptime(selected_date, "%Y-%m-%d").year
        return datetime.date(year, month, 1)

    def get_month_enddate(self, selected_date):
        month = datetime.datetime.strptime(selected_date, "%Y-%m-%d").month
        year = datetime.datetime.strptime(selected_date, "%Y-%m-%d").year

        if month in (4, 6, 9, 11):
            return datetime.date(year, month, 30)
        elif month == 2:
            if year % 4 == 0:
                return datetime.date(year, month, 29)
            else:
                return datetime.date(year, month, 28)
        else:
            return datetime.date(year, month, 31)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

worklogger/logs/forms.py
from django import forms

from .models import Log


class DateInput(forms.DateInput):
    input_type = 'date'


class LogForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = ('duration', 'project', 'log_date')
        widgets = {
            'log_date': DateInput()
        }

worklogger/logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import template, forms
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.db.models import Sum
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required

from .models import Log, Project
from .forms import LogForm


# Create your views here.
class LogIndexView(generic.ListView):
    template_name = 'logs/index.html'
    context_object_name = 'logs_list'

    def get_queryset(self):
        user = self.request.user
        filter_value = self.request.GET.get('filter')
        view = self.request.GET.get('view')
        logs = Log.objects.filter(user=user)

        # If a date is selected, filter to that date
        if filter_value:

            if view == 'week':
                logs = user.profile.get_week_logs(filter_value)

            elif view == 'month':
                startdate = user.profile.get_month_startdate(filter_value)
                enddate = user.profile.get_month_enddate(filter_value)
                logs = logs.filter(log_date__gte=startdate).filter(log_date__lte=enddate)

            else:
                logs = Log.objects.filter(log_date=filter_value)

        user.profile.total_hours = logs.aggregate(Sum('duration'))['duration__sum']

        return logs


class LogDetail(generic.DetailView):
    model = Log
    template_name = 'logs/detail.html'


class LogDelete(DeleteView):
    model = Log
    success_url = reverse_lazy('logs:index')
    template_name = 'logs/delete.html'


class LogUpdate(UpdateView):
    model = Log
    fields = ['log_date']
    template_name_suffix = '_update'
    success_message = "Log updated"

    def get_success_url(self):
        return reverse('logs:detail', kwargs={'pk': self.object.pk})


class LogNew(CreateView):
    model = Log
    template_name = 'logs/new.html'
    form_class = LogForm


class LogForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = ('project', 'duration', 'log_date')
        widgets = {'log_date': forms.DateField()}


def home(request):
    return render(request, 'home.html')

worklogger/logs/templates/logs/delete.html
<div class="modal-content">
    <div class="modal-header">
        <h3>Delete Log</h3>
    </div>
    <div class="modal-body">
        {% if request.user == object.user %}
            <p>Are you sure you want to delete this object?</p>

            <form action="{% url 'logs:delete' log.pk %}" method="POST"> 
                {% csrf_token %}
                <input type="submit" value="Delete" class="btn btn-primary"/>
                <input type="button" value="Cancel" onclick="window.location='{% url 'logs:index' %}'" class="btn btn-primary"/>
            </form>

        {% else %}
            <h4>You're not allowed to be here.</h4>
            <a href="{% url 'logs:index' %}">Dashboard</a>
        {% endif %}
    </div>
    <div class="modal-footer">
        
    </div>
</div>




    

worklogger/logs/templates/logs/detail.html
<h1>{{ log.log_date }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

Hours logged: {{ log.duration }}<br/>
Project: {{ log.project }}<br/>
Date logged: {{ log.date_logged }}

worklogger/logs/templates/logs/edit.html
{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

worklogger/logs/templates/logs/index.html
{% load static %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'logs/style.css' %}" />
	<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    {% block content %}

	<div class="container-fluid">
		{% if user.is_authenticated %}

		  Hi {{ user.username }}! <a href="{% url 'logout' %}">Logout</a><br><br>

			<form action="{% url 'logs:index' %}" method="get">
				{% csrf_token %}
				<label for="">Choose a date: </label>
				<input type="text" id="datepicker" name="filter"><br>
				<label for="">View logs by: </label>
				<select name="view">
					<option value="day">Selected day</option>
					<option value="week">Week</option>
					<option value="month">Month</option>n>
				</select>
				<input type="submit" value="Filter" class="btn btn-info"/>
			</form>
			<script>
			$( "#datepicker" ).datepicker({
				dateFormat: "yy-mm-dd",
				changeMonth: true,
				numberOfMonths: 1,
			});
			$( "#datepicker" ).datepicker("setDate", 'today');
			</script>

			<h5>Total hours: {{ user.profile.total_hours }} hr{{user.profile.total_hours|pluralize}} </h5>
		
			{% if logs_list %}
			<table class="loglist">
				<tr>
					<th>Date</th>
					<th>Hours</th>
					<th>Project</th>
					<th>Actions</th>
				</tr>

				{% for log in logs_list %}

				<tr>
					<td> {{ log.log_date }} </td>
					<td>
						{% if log.date_logged > log.log_date %}
							<a href="{% url 'logs:detail' log.id%}" class="late-logs">{{ log.duration }} hr{{log.duration|pluralize}}</a> 
						{% else %}
							<a href="{% url 'logs:detail' log.id %}">{{ log.duration }} hr{{log.duration|pluralize}}</a>
						{% endif %}
					</td>
					<td> {{ log.project }} </td>
					<td>
						&nbsp;
						<a href="{% url 'logs:delete' log.pk %}" data-toggle="modal" data-target="#deleteLogModal" title="Delete Log"><i class="fas fa-trash-alt"></i></a>&nbsp;
						<a href="{% url 'logs:update' log.pk %}" title="Move to date" id="datepicker"><i class="fas fa-calendar-alt"></i></a>

					    <!-- Modal HTML -->
					    <div id="deleteLogModal" class="modal fade">
					        <div class="modal-dialog">
					            <div class="modal-content">
					                <!-- Content will be loaded here from "remote.php" file -->
					            </div>
					        </div>
					    </div>

                        <script type="text/javascript">
                            $(function () {
                                $('#datepicker').datepicker({
                                    inline: true,
                                    sideBySide: true
                                });
                            });
                            $("#datepicker").click(function() {
                                $("#datepicker").datepicker("show");
                            });
                        </script>
					</td>
				</tr>

				{% endfor %}

			</table><br>
			{% else %}
				<p>No logs for this day.</p>
			{% endif %}
			<br>

			<a href="{% url 'logs:new' %}" class="btn btn-primary">Log</a>
            {% include 'logs/new.html' %}

		{% else %}
		  <p>You are not logged in</p>
		  <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
		{% endif %}
	</div>
</body>
{% endblock %}

worklogger/logs/templates/logs/log_update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>

worklogger/logs/templates/logs/new.html
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
</head>

<form action="{% url 'logs:new' %}" method="post">
	{% csrf_token %}
    {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}<br/>
        
    {% endfor %}
    <input type="submit" value="Save" />
</form>
<script>
$( "#datepicker" ).datepicker({
    dateFormat: "mm-dd-yy",
    changeMonth: true,
    numberOfMonths: 1,
});
$( "#datepicker" ).datepicker("setDate", 'today');
</script>

worklogger/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Worklogger{% endblock %}</title>
</head>
<body>
    <main>
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

worklogger/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container-fluid">
    {% if user.is_authenticated %}
        <p> Hi {{ user.username }}! <a href="{% url 'logout' %}">Logout</a> </p>
        <div><a href="{% url 'logs:index' %}">See logs</a><div><br>
        <div><a href="{% url 'logs:new' %}">Log</a><div><br>

    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</div>
{% endblock %}